-- Elite English Academy Full CMS migration - run AFTER supabase/schema.sql
create table if not exists public.settings (key text primary key, value text, updated_at timestamptz not null default now());
alter table public.courses add column if not exists mode text;
alter table public.courses add column if not exists level text;
alter table public.courses add column if not exists sort_order int default 0;
alter table public.courses add column if not exists is_active boolean default true;
alter table public.courses add column if not exists updated_at timestamptz default now();
alter table public.gallery add column if not exists is_active boolean default true;
alter table public.gallery add column if not exists sort_order int default 0;
create table if not exists public.navigation_links (id uuid primary key default gen_random_uuid(), label text not null, href text not null, sort_order int default 0, is_active boolean default true, created_at timestamptz not null default now());
create table if not exists public.hero_slides (id uuid primary key default gen_random_uuid(), badge text, title text not null, subtitle text, description text, image_url text, primary_button_text text default 'Free Demo Class', primary_button_link text default '/admission', secondary_button_text text default 'View Courses', secondary_button_link text default '/courses', sort_order int default 0, is_active boolean default true, created_at timestamptz not null default now());
create table if not exists public.page_sections (id uuid primary key default gen_random_uuid(), slug text unique not null, page text default 'home', section_type text default 'custom', eyebrow text, title text, subtitle text, description text, image_url text, button_text text, button_link text, secondary_button_text text, secondary_button_link text, sort_order int default 0, is_active boolean default true, created_at timestamptz not null default now(), updated_at timestamptz not null default now());
create table if not exists public.section_items (id uuid primary key default gen_random_uuid(), section_slug text not null, title text not null, description text, icon text, image_url text, link_text text, link_href text, sort_order int default 0, is_active boolean default true, created_at timestamptz not null default now());
create table if not exists public.stats (id uuid primary key default gen_random_uuid(), label text not null, value numeric not null default 0, suffix text default '', icon text default 'Sparkles', sort_order int default 0, is_active boolean default true, created_at timestamptz not null default now());
create table if not exists public.features (id uuid primary key default gen_random_uuid(), section_slug text not null default 'why-choose-us', title text not null, description text, icon text default 'BadgeCheck', sort_order int default 0, is_active boolean default true, created_at timestamptz not null default now());
create table if not exists public.social_links (id uuid primary key default gen_random_uuid(), platform text not null, label text, url text not null, sort_order int default 0, is_active boolean default true, created_at timestamptz not null default now());
create table if not exists public.footer_links (id uuid primary key default gen_random_uuid(), group_name text not null default 'quick_links', label text not null, href text default '#', sort_order int default 0, is_active boolean default true, created_at timestamptz not null default now());
-- seeds: navigation
insert into public.navigation_links (label, href, sort_order) select * from (values ('Home','/',0),('About','/about',1),('Courses','/courses',2),('Gallery','/gallery',3),('Admission','/admission',4),('Contact','/contact',5)) as v(label,href,sort_order) where not exists (select 1 from public.navigation_links);
-- seeds: hero
insert into public.hero_slides (badge,title,description,image_url,sort_order) select 'Admissions Open 2026','Speak English with Confidence. Build Your Future.','Master Spoken English, IELTS preparation, grammar foundations, and practical communication skills with expert-led training designed for real-world success.','/hero/Teacher-portrait.png',0 where not exists (select 1 from public.hero_slides);
-- seeds: sections
insert into public.page_sections (slug,page,section_type,eyebrow,title,description,image_url,button_text,button_link,sort_order) values ('home-about','home','about','About Elite English Academy','Meet Our Expert English Trainer','At Elite English Academy, we help learners build real confidence through practical communication, strong grammar foundations, and result-driven preparation.','/hero/teacher-about.png','Book Free Demo','/admission',10),('home-cta','home','cta','Start today','Ready to Speak English with Confidence?','Join expert-led speaking classes, practical communication training, and a supportive learning environment designed to help you grow fast.',NULL,'WhatsApp Now','https://wa.me/918888711228',60),('mission','home','mission','Our Mission','Confident Communicators','To empower every learner with practical speaking skills and self-confidence.',NULL,NULL,NULL,11),('vision','home','vision','Our Vision','Lifelong Success','To be the region most trusted English academy.',NULL,NULL,NULL,12) on conflict (slug) do nothing;
insert into public.section_items (section_slug,title,sort_order) values ('home-about','Spoken English',0),('home-about','IELTS and PTE Preparation',1),('home-about','Grammar and Vocabulary',2),('home-about','Personality Development',3) on conflict do nothing;
insert into public.stats (label,value,suffix,icon,sort_order) select * from (values ('Happy Students',500,'+','GraduationCap',0),('Years Teaching Experience',12,'+','BookOpen',1),('Online and Offline Classes',2,'','Laptop',2),('Practical Speaking Focus',100,'%','Sparkles',3)) as v(label,value,suffix,icon,sort_order) where not exists (select 1 from public.stats);
insert into public.features (section_slug,title,description,icon,sort_order) select * from (values ('why-choose-us','Daily Speaking Practice','Build real confidence through guided speaking drills.','MessageSquare',0),('why-choose-us','Small Batch Size','Personal attention and focused mentorship.','GraduationCap',1),('why-choose-us','Weekly Assessments','Structured evaluations and feedback every week.','BookOpen',2),('why-choose-us','Modern Study Material','Updated resources for interviews and exams.','Briefcase',3),('why-choose-us','Certificate After Completion','Recognized certificate for your growth.','BadgeCheck',4),('why-choose-us','Online and Offline Classes','Choose the mode that fits your schedule.','Laptop',5)) as v(section_slug,title,description,icon,sort_order) where not exists (select 1 from public.features);
insert into public.social_links (platform,label,url,sort_order) select * from (values ('WhatsApp','WhatsApp','https://wa.me/918888711228',0),('Instagram','Instagram','https://www.instagram.com/eliteenglishacademy',1),('Facebook','Facebook','https://facebook.com/eliteenglishacademy',2),('YouTube','YouTube','https://youtube.com/@eliteenglishacademy',3)) as v(platform,label,url,sort_order) where not exists (select 1 from public.social_links);
insert into public.footer_links (group_name,label,href,sort_order) select * from (values ('quick_links','About Us','/about',0),('quick_links','Courses','/courses',1),('quick_links','Gallery','/gallery',2),('quick_links','Admission','/admission',3),('quick_links','Contact','/contact',4),('courses','Spoken English','/courses',0),('courses','IELTS Preparation','/courses',1),('courses','Grammar and Vocabulary','/courses',2),('courses','Teacher Training','/courses',3)) as v(group_name,label,href,sort_order) where not exists (select 1 from public.footer_links);
