-- Elite English Academy Full CMS migration - run AFTER supabase/schema.sql
create table if not exists public.settings (key text primary key, value text, updated_at timestamptz not null default now());
alter table public.courses add column if not exists mode text;
alter table public.courses add column if not exists level text;
alter table public.courses add column if not exists sort_order int default 0;
alter table public.courses add column if not exists is_active boolean default true;
alter table public.courses add column if not exists updated_at timestamptz default now();
alter table public.gallery add column if not exists is_active boolean default true;
alter table public.gallery add column if not exists sort_order int default 0;
create table if not exists public.navigation_links (id uuid primary key default gen_random_uuid(), label text not null, href text not null, sort_order int default 0, is_active boolean default true, created_at timestamptz not null default now());
create table if not exists public.hero_slides (id uuid primary key default gen_random_uuid(), badge text, title text not null, subtitle text, description text, image_url text, primary_button_text text default 'Free Demo Class', primary_button_link text default '/admission', secondary_button_text text default 'View Courses', secondary_button_link text default '/courses', sort_order int default 0, is_active boolean default true, created_at timestamptz not null default now());
create table if not exists public.stats (id uuid primary key default gen_random_uuid(), label text not null, value numeric not null default 0, suffix text default '', icon text default 'Sparkles', sort_order int default 0, is_active boolean default true, created_at timestamptz not null default now());
create table if not exists public.features (id uuid primary key default gen_random_uuid(), section_slug text not null default 'why-choose-us', title text not null, description text, icon text default 'BadgeCheck', sort_order int default 0, is_active boolean default true, created_at timestamptz not null default now());
create table if not exists public.social_links (id uuid primary key default gen_random_uuid(), platform text not null, label text, url text not null, sort_order int default 0, is_active boolean default true, created_at timestamptz not null default now());
create table if not exists public.footer_links (id uuid primary key default gen_random_uuid(), group_name text not null default 'quick_links', label text not null, href text default '#', sort_order int default 0, is_active boolean default true, created_at timestamptz not null default now());
-- seeds: navigation
insert into public.navigation_links (label, href, sort_order) select * from (values ('Home','/',0),('About','/about',1),('Courses','/courses',2),('Gallery','/gallery',3),('Admission','/admission',4),('Contact','/contact',5)) as v(label,href,sort_order) where not exists (select 1 from public.navigation_links);
-- seeds: hero
insert into public.hero_slides (badge,title,description,image_url,sort_order) select 'Admissions Open 2026','Speak English with Confidence. Build Your Future.','Master Spoken English, IELTS preparation, grammar foundations, and practical communication skills with expert-led training designed for real-world success.','/hero/Teacher-portrait.png',0 where not exists (select 1 from public.hero_slides);
insert into public.stats (label,value,suffix,icon,sort_order) select * from (values ('Happy Students',500,'+','GraduationCap',0),('Years Teaching Experience',12,'+','BookOpen',1),('Online and Offline Classes',2,'','Laptop',2),('Practical Speaking Focus',100,'%','Sparkles',3)) as v(label,value,suffix,icon,sort_order) where not exists (select 1 from public.stats);
insert into public.features (section_slug,title,description,icon,sort_order) select * from (values ('why-choose-us','Daily Speaking Practice','Build real confidence through guided speaking drills.','MessageSquare',0),('why-choose-us','Small Batch Size','Personal attention and focused mentorship.','GraduationCap',1),('why-choose-us','Weekly Assessments','Structured evaluations and feedback every week.','BookOpen',2),('why-choose-us','Modern Study Material','Updated resources for interviews and exams.','Briefcase',3),('why-choose-us','Certificate After Completion','Recognized certificate for your growth.','BadgeCheck',4),('why-choose-us','Online and Offline Classes','Choose the mode that fits your schedule.','Laptop',5)) as v(section_slug,title,description,icon,sort_order) where not exists (select 1 from public.features);
insert into public.social_links (platform,label,url,sort_order) select * from (values ('WhatsApp','WhatsApp','https://wa.me/918888711228',0),('Instagram','Instagram','https://www.instagram.com/eliteenglishacademy',1),('Facebook','Facebook','https://facebook.com/eliteenglishacademy',2),('YouTube','YouTube','https://youtube.com/@eliteenglishacademy',3)) as v(platform,label,url,sort_order) where not exists (select 1 from public.social_links);
insert into public.footer_links (group_name,label,href,sort_order) select * from (values ('quick_links','About Us','/about',0),('quick_links','Courses','/courses',1),('quick_links','Gallery','/gallery',2),('quick_links','Admission','/admission',3),('quick_links','Contact','/contact',4),('courses','Spoken English','/courses',0),('courses','IELTS Preparation','/courses',1),('courses','Grammar and Vocabulary','/courses',2),('courses','Teacher Training','/courses',3)) as v(group_name,label,href,sort_order) where not exists (select 1 from public.footer_links);
insert into public.settings (key,value) values ('academy_name','Elite''s English Academy'),('tagline','Learn English - Teach English - Build Your Career'),('phone_display','+91 88887 11228'),('phone_href','tel:+918888711228'),('whatsapp_number','918888711228'),('email','elitejamesw182025@gmail.com'),('address','Near Sai Deep Hospital, Mondha Naka, Georai, Beed, Maharashtra 431127'),('instagram_url','https://www.instagram.com/eliteenglishacademy'),('facebook_url','https://facebook.com/eliteenglishacademy'),('youtube_url','https://youtube.com/@eliteenglishacademy'),('logo_url','/vercel.png'),('business_hours','Mon - Sat: 7:00 AM - 9:00 PM'),('footer_about','Practical English training for speaking, exams and everyday success.'),('copyright_text','All Rights Reserved.'),('announcement_title','Admissions Open 2026'),('announcement_text','Book your free demo class today and start speaking English with confidence!') on conflict (key) do nothing;
alter table public.navigation_links enable row level security;
alter table public.hero_slides enable row level security;
alter table public.stats enable row level security;
alter table public.features enable row level security;
alter table public.social_links enable row level security;
alter table public.footer_links enable row level security;
alter table public.admissions enable row level security;
alter table public.contacts enable row level security;
create policy "Public read navigation" on public.navigation_links for select using (true);
create policy "Public read heroes" on public.hero_slides for select using (true);
create policy "Public read stats" on public.stats for select using (true);
create policy "Public read features" on public.features for select using (true);
create policy "Public read socials" on public.social_links for select using (true);
create policy "Public read footer" on public.footer_links for select using (true);
create policy "Admin nav" on public.navigation_links for all to authenticated using (true) with check (true);
create policy "Admin heroes" on public.hero_slides for all to authenticated using (true) with check (true);
create policy "Admin stats" on public.stats for all to authenticated using (true) with check (true);
create policy "Admin features" on public.features for all to authenticated using (true) with check (true);
create policy "Admin socials" on public.social_links for all to authenticated using (true) with check (true);
create policy "Admin footer" on public.footer_links for all to authenticated using (true) with check (true);
create policy "Admin courses" on public.courses for all to authenticated using (true) with check (true);
create policy "Admin gallery" on public.gallery for all to authenticated using (true) with check (true);
create policy "Admin notices" on public.notices for all to authenticated using (true) with check (true);
create policy "Admin testimonials" on public.testimonials for all to authenticated using (true) with check (true);
create policy "Admin batches" on public.batches for all to authenticated using (true) with check (true);
create policy "Admin faqs" on public.faqs for all to authenticated using (true) with check (true);
create policy "Admin stories" on public.success_stories for all to authenticated using (true) with check (true);
create policy "Admin trainers" on public.trainers for all to authenticated using (true) with check (true);
create policy "Admin settings" on public.settings for all to authenticated using (true) with check (true);
create policy "Admin admissions" on public.admissions for all to authenticated using (true) with check (true);
create policy "Admin contacts" on public.contacts for all to authenticated using (true) with check (true);
insert into storage.buckets (id, name, public) values ('site-assets','site-assets',true),('logos','logos',true) on conflict (id) do nothing;
